services:

  db:
    image: postgres:15
    container_name: db
    env_file:
      - ../.env
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    container_name: foodgram-back
    build:
      context: ../backend
      dockerfile: Dockerfile
    volumes:
      - ../backend/:/app/
      - static:/app/static/
      - media:/app/media/
    env_file:
      - ../.env
    environment:
      - USE_SQLITE=False
    depends_on:
      - db
    command: >
      sh -c "until nc -z db 5432; do echo 'Ожидаем базу данных...'; sleep 2; done &&
             python manage.py migrate --noinput &&
             python manage.py collectstatic --noinput &&
             gunicorn foodgram.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - "8000:8000"


  frontend:
    container_name: foodgram-front
    build: ../frontend
    volumes:
      - ../frontend/:/app/result_build/

  nginx:
    container_name: foodgram-proxy
    image: nginx:1.25.4-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static:/app/static/
      - media:/app/media/
    depends_on:
      - frontend
      - backend


volumes:
  pgdata:
  static:
  media: