services:

  db:
    image: postgres:15
    container_name: db
    env_file:
      - ../.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "6543:5432"

  backend:
    container_name: backend
    build:
      context: ../backend
      dockerfile: Dockerfile
    volumes:
      - ../backend/:/app/                 # Исходники бекенда
      - static:/app/static/              # Статические файлы, общие volume
      - media:/app/media/                # Медиа файлы, общие volume
    env_file:
      - ../.env
    environment:
      - USE_SQLITE=False
    depends_on:
      - db
    command: >
      sh -c "until nc -z db 5432; do echo 'Ожидаем базу данных...'; sleep 2; done &&
             python manage.py migrate --noinput &&
             python manage.py collectstatic --noinput &&
             gunicorn foodgram.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - "8000:8000"

  frontend:
    container_name: frontend
    build: ../frontend
    command: sh -c "cp -r build/* /frontend_build/"
    volumes:
      - ../frontend/:/app/result_build/  # Исходники фронтенда
      - frontend_build:/frontend_build/  # Отдельный volume для собранных файлов фронтенда

  nginx:
    container_name: nginx
    image: nginx:1.25.4-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf   # Конфиг nginx
      - frontend_build:/usr/share/nginx/html/        # Собранный фронтенд
      - ../docs/:/usr/share/nginx/html/api/docs/     # Документация
      - static:/app/static/                           # Статика Django
      - media:/app/media/                             # Медиа Django
    depends_on:
      - frontend
      - backend

volumes:
  pgdata:
  static:
  media:
  frontend_build: